service: express-js-ts-service-template
plugins:
  - serverless-plugin-typescript-express
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 29
  region: eu-west-1

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
